<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	name="PowerService"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:req="http://nl.hu.iac/powerservice/request"
	xmlns:rsp="http://nl.hu.iac/powerservice/response"
	xmlns:flt="http://nl.hu.iac/powerservice/fault"
	xmlns="http://nl.hu.iac/powerservice/"
	targetNamespace="http://nl.hu.iac/powerservice/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://nl.hu.iac/powerservice/request"
				schemaLocation="request.xsd"/>
			<xsd:import namespace="http://nl.hu.iac/powerservice/response"
				schemaLocation="response.xsd"/>
			<xsd:import namespace="http://nl.hu.iac/powerservice/fault"
				schemaLocation="fault.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="request">
		<wsdl:part name="request" element="req:powerRequest"/>
	</wsdl:message>
	<wsdl:message name="response">
		<wsdl:part name="response" element="rsp:powerResponse"/>
	</wsdl:message>
	<wsdl:message name="fault">
		<wsdl:part name="fault" element="flt:powerFault"/>
	</wsdl:message>
	<wsdl:portType name="powerServiceInterface">
		<wsdl:operation name="calculatePower">
			<wsdl:input message="request"/>
			<wsdl:output message="response"/>
			<wsdl:fault name="fault" message="fault"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="powerServiceBinding" type="powerServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="calculatePower">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault name="fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="powerServiceService">
		<wsdl:port name="WS-Port" binding="powerServiceBinding">
			<soap:address location="http://localhost:8080/ws-producer/soap"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>