
package nl.rls.ci.soap.dto;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LIReceiveMessageService", targetNamespace = "http://uic.cc.org/UICMessage", wsdlLocation = "file:/C:/workspace/trains24/trains24_ci_client/src/main/resources/UICCCMessageProcessingInboundWS.wsdl")
public class LIReceiveMessageService
    extends Service
{

    private final static URL LIRECEIVEMESSAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(nl.rls.ci.soap.dto.LIReceiveMessageService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = nl.rls.ci.soap.dto.LIReceiveMessageService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/workspace/trains24/trains24_ci_client/src/main/resources/UICCCMessageProcessingInboundWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace/trains24/trains24_ci_client/src/main/resources/UICCCMessageProcessingInboundWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LIRECEIVEMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public LIReceiveMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LIReceiveMessageService() {
        super(LIRECEIVEMESSAGESERVICE_WSDL_LOCATION, new QName("http://uic.cc.org/UICMessage", "LIReceiveMessageService"));
    }

    /**
     * 
     * @return
     *     returns UICReceiveMessage
     */
    @WebEndpoint(name = "UICReceiveMessagePort")
    public UICReceiveMessage getUICReceiveMessagePort() {
        return super.getPort(new QName("http://uic.cc.org/UICMessage", "UICReceiveMessagePort"), UICReceiveMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UICReceiveMessage
     */
    @WebEndpoint(name = "UICReceiveMessagePort")
    public UICReceiveMessage getUICReceiveMessagePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uic.cc.org/UICMessage", "UICReceiveMessagePort"), UICReceiveMessage.class, features);
    }

}
